In [1]:
import cv2
import numpy as np

red = np.uint8([[[0,0,255]]])
hsv_red = cv2.cvtColor(red,cv2.COLOR_BGR2HSV)
print(hsv_red)

[[[  0 255 255]]]


In [2]:
one = np.uint8([[[55, 57, 139]]])
hsv_one = cv2.cvtColor(one, cv2.COLOR_BGR2HSV)
print(hsv_one)

[[[  1 154 139]]]


In [3]:
two = np.uint8([[[33, 147, 166]]])
hsv_two = cv2.cvtColor(two, cv2.COLOR_BGR2HSV)
print(hsv_two)

[[[ 26 204 166]]]


In [4]:
three = np.uint8([[[23, 102, 44]]])
hsv_three = cv2.cvtColor(three, cv2.COLOR_BGR2HSV)
print(hsv_three)

[[[ 52 198 102]]]


In [5]:
four = np.uint8([[[23, 81, 6]]])
hsv_four = cv2.cvtColor(four, cv2.COLOR_BGR2HSV)
print(hsv_four)

[[[ 67 236  81]]]


In [6]:
five = np.uint8([[[51,97,37]]])
hsv_five = cv2.cvtColor(five, cv2.COLOR_BGR2HSV)
print(hsv_five)

[[[ 67 158  97]]]


In [7]:
six = np.uint8([[[91,69,5]]])
hsv_six = cv2.cvtColor(six, cv2.COLOR_BGR2HSV)
print(hsv_six)

[[[ 98 241  91]]]


In [8]:
seven = np.uint8([[[109, 38, 18]]])
hsv_seven = cv2.cvtColor(seven, cv2.COLOR_BGR2HSV)
print(hsv_seven)

[[[113 213 109]]]


In [9]:
eight = np.uint8([[[85, 30, 58]]])
hsv_eight = cv2.cvtColor(eight, cv2.COLOR_BGR2HSV)
print(hsv_eight)

[[[135 165  85]]]


In [10]:
nine = np.uint8([[[68, 25, 114]]])
hsv_nine = cv2.cvtColor(nine, cv2.COLOR_BGR2HSV)
print(hsv_nine)

[[[166 199 114]]]


In [11]:
ten = np.uint8([[[54, 38, 116]]])
hsv_ten = cv2.cvtColor(ten, cv2.COLOR_BGR2HSV)
print(hsv_ten)

[[[174 171 116]]]


In [2]:
cap = np.uint8([[[63, 15, 1]]])
hsv_cap = cv2.cvtColor(cap, cv2.COLOR_BGR2HSV)
print(hsv_cap)

[[[113 251  63]]]
